### ISSUE TITLE
Badly formatted entries in distance matrix

### ISSUE THREAD

**Issue by biomendi** [mptrsen/distats#2]
Hi,

The resulting distance matrix contains errors or badly formatted entries in some lines. I attach my alignment ([C0614418.fasta.txt](https://github.com/mptrsen/distats/files/10497725/C0614418.fasta.txt)) and its corresponding distance matrix ([distance_matrix_C0614418.csv.txt](https://github.com/mptrsen/distats/files/10497792/distance_matrix_C0614418.csv.txt)) resulting from distats. You could check lines 71911, 71943 or 72009 in the distance matrix to find some badly formatted entries. Please notice that I manually added the extension .txt so that I could upload them in this thread. The command that I used is this one:

```perl distats.pl C0614418.fasta C0614418.csv --num_threads 40 --distance k2p --print_dist_matrix```

Any idea on how can I solve this issue?

Thanks!

**Comment by mptrsen** [comment]
Hi,

this looks to be a race condition issue that lets two processes write to the file at the same time. Can you try with fewer threads (even single-threaded)? That should reduce the likelihood of such a collision. Your fasta file is not *that* large.

I have moved three positions since publishing this and my priorities have moved elsewhere so I can not develop distats any further. I hope you don't run into additional issues!

Feel free to reopen this issue again if needed.
